data = [{
    name: "心灵奇旅 Soul",
    director: "彼特·道格特/凯普·鲍尔斯",
    rate: 8.8,
    genres: "动画/音乐/奇幻",
    page_url: "https://movie.douban.com/subject/24733428/",
    region: "美国",
    imdb: "tt2948372",
    brief: "究竟是什么塑造了真正的你？电影将聚焦乔伊·高纳（杰米·福克斯配音）。这位中学音乐老师获得了梦寐以求的机会——在纽约最好的爵士俱乐部演奏。但一个小失误把他从纽约的街道带到了一个奇幻的地方“生之来处”（the Great Before）。在那里，灵魂们获得培训，在前往地球之前将获得他们的个性特点和兴趣。决心要回到地球生活的乔伊认识了一个早熟的灵魂“二十二”（蒂娜·菲 配音），二十二一直找不到自己对于人类生活的兴趣。随着乔伊不断试图向二十二展示生命的精彩之处，他也将领悟一些人生终极问题的答案。",
    img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2626308994.webp",
    probability: { "惊悚": 0.8, "xiju": 0.5 },
    targets: [{
            name: "天空之城 天空の城ラピュタ",
            page_url: "https://movie.douban.com/subject/1291583/?from=subject-page",
            img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1446261379.webp",
            similarity: "90%",
            probability: { "惊悚": 0.8, "xiju": 0.5 }
        },
        {
            name: "哈尔的移动城堡",
            page_url: "https://movie.douban.com/subject/1308807/?from=subject-page",
            img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2174346180.webp",
            similarity: "90%",
        },
        {
            name: "玩具总动员",
            page_url: "https://movie.douban.com/subject/1291575/?from=subject-page",
            img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2565956404.webp",
            similarity: "88%",
        },
        {
            name: "幽灵公主",
            page_url: "https://movie.douban.com/subject/1297359/?from=subject-page",
            img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1613191025.webp",
            similarity: "86%",
        },
        {
            name: "千与千寻",
            page_url: "https://movie.douban.com/subject/1291561/?from=subject-page",
            img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2557573348.webp",
            similarity: "82%",
        },
        {
            name: "头脑特工队",
            page_url: "https://movie.douban.com/subject/10533913/?from=subject-page",
            img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2266293606.webp",
            similarity: "80%",
        },
        {
            name: "红辣椒",
            page_url: "https://movie.douban.com/subject/1865703/?from=subject-page",
            img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p456825720.webp",
            similarity: "80%",
        },
        {
            name: "怪兽电力公司",
            page_url: "https://movie.douban.com/subject/1291579/?from=subject-page",
            img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2513247938.webp",
            similarity: "78%",
        },
        {
            name: "东京教父",
            page_url: "https://movie.douban.com/subject/1310177/?from=subject-page",
            img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p456703618.webp",
            similarity: "77%",
        },
        {
            name: "哪吒之魔童降世",
            page_url: "https://movie.douban.com/subject/26794435/?from=subject-page",
            img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
            similarity: "75%",
        },
    ],
},
{
    name: "侍神令",
    director: "李蔚然",
    rate: 5.8,
    genres: "奇幻",
    page_url: "https://movie.douban.com/subject/26935283/?from=subject-page",
    region: "中国大陆",
    imdb: "tt12151820",
    brief: "穿行于人妖两界的阴阳师晴明（陈坤 饰），因与一众妖怪缔结契约，酿成大祸，深陷危机。而与此同时，妖皇势力正卷土重来，一场恶战一触即发。在风云突变、局势动荡的危急时刻，晴明恍然发现，自己人妖混血的身份，竟是这一切灾祸的关键......",
    img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2629260713.webp",
    targets: [{
            name: "冷血狂宴",
            page_url: "https://movie.douban.com/subject/26673282/?from=subject-page",
            img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2627806003.webp",
            similarity: "88%",
            probability: { '动画': 1, '奇幻': 2, '冒险': 3, '剧情': 4, '动作': 5, '爱情': 6, '悬疑': 7, '惊悚': 8, '犯罪': 9, '同性': 10 }
        }
    },
    {
        name: "怪物先生",
        page_url: "https://movie.douban.com/subject/30150727/?from=subject-page",
        img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2616835570.webp",
        similarity: "86%",
    },
    {
        name: "赤狐书生",
        page_url: "https://movie.douban.com/subject/30464542/?from=subject-page",
        img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2627575957.webp",
        similarity: "82%",
    },
    {
        name: "晴雅集",
        page_url: "https://movie.douban.com/subject/30284141/?from=subject-page",
        img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2622484010.webp",
        similarity: "78%",
    },
    {
        name: "新神榜：哪吒重生",
        page_url: "https://movie.douban.com/subject/34779692/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2631711326.webp",
        similarity: "75%",
    },
    {
        name: "沉睡魔咒2",
        page_url: "https://movie.douban.com/subject/26426056/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2570105165.webp",
        similarity: "73%",
    },
    {
        name: "刺杀小说家",
        page_url: "https://movie.douban.com/subject/26826330/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2628440875.webp",
        similarity: "73%",
    },
    {
        name: "女巫",
        page_url: "https://movie.douban.com/subject/3346423/?from=subject-page",
        img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2621884130.webp",
        similarity: "70%",
    },
    {
        name: "摸金校尉之九幽将军",
        page_url: "https://movie.douban.com/subject/26986120/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2532339096.webp",
        similarity: "68%",
    },
    {
        name: "姜子牙",
        page_url: "https://movie.douban.com/subject/25907124/?from=subject-page",
        img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2621219978.webp",
        similarity: "68%",
    },
],
}, {
name: "小妇人 Little Women",
director: "格蕾塔·葛韦格",
rate: 8.1,
genres: "剧情/爱情",
page_url: "https://movie.douban.com/subject/26348103/?from=subject-page",
region: "美国",
imdb: "tt3281548",
brief: "马奇夫人（劳拉·邓恩 Laura Dern 饰）有着四个如花似玉的女儿，大女儿乔（西尔莎·罗南 Saoirse Ronan 饰）满脑子塞着古灵精怪的念头，整天拿着蘸水笔东写西写，她的故事在全家上下都受到了热烈的欢迎。二女儿梅格（艾玛·沃森 Emma Watson 饰）拥有着美丽的外表，和对于爱情的天真憧憬。三女儿艾米（佛罗伦斯·珀 Florence Pugh 饰）渴望成为一名画家。最小的女儿贝斯（伊莱扎·斯坎伦 Eliza Scanlen 饰）虽然个性比起三个姐姐要来的内向的多，却拥有接触的音乐天赋。在马奇夫人的教导之下， 四个姑娘渐渐成长为了拥有独立人格的杰出女性， 她们热情、 乐观、 善良， 每个人都在各自的道路上坚强而又坚定的前进着。 ",
img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2572813215.webp",
targets: [{
        name: "伯德小姐",
        page_url: "https://movie.douban.com/subject/26588314/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2505925363.webp",
        similarity: "95%",
    },
    {
        name: "婚姻故事",
        page_url: "https://movie.douban.com/subject/27202818/?from=subject-page",
        img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2571760178.webp",
        similarity: "93%",
    },
    {
        name: "傲慢与偏见",
        page_url: "https://movie.douban.com/subject/1418200/?from=subject-page",
        img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2016401659.webp",
        similarity: "90%",
    },
    {
        name: "怦然心动",
        page_url: "https://movie.douban.com/subject/3319755/?from=subject-page",
        img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p501177648.webp",
        similarity: "90%",
    },
    {
        name: "82年生的金智英",
        page_url: "https://movie.douban.com/subject/30327842/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2578045524.webp",
        similarity: "88%",
    },
    {
        name: "过春天",
        page_url: "https://movie.douban.com/subject/27191431/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2549537782.webp",
        similarity: "86%",
    },
    {
        name: "爱在黎明破晓前",
        page_url: "https://movie.douban.com/subject/1296339/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2555762374.webp",
        similarity: "86%",
    },
    {
        name: "请以你的名字呼唤我",
        page_url: "https://movie.douban.com/subject/26799731/?from=subject-page",
        img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2505525050.webp",
        similarity: "85%",
    },
    {
        name: "纽约的一个雨天",
        page_url: "https://movie.douban.com/subject/27089612/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2556824333.webp",
        similarity: "83%",
    },
    {
        name: "爱乐之城",
        page_url: "https://movie.douban.com/subject/25934014/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2395517414.webp",
        similarity: "82%",
    },
],
}, {
name: "过春天",
director: "白雪",
rate: 7.7,
genres: "剧情",
page_url: "https://movie.douban.com/subject/27191431/?from=subject-page",
region: "中国大陆",
imdb: "tt8875366",
brief: "单亲家庭出身的16岁女学生佩佩（黄尧 饰），她的城市既是香港、也是深圳，白天在香港上学，晚上回到深圳跟妈妈（倪虹洁 饰）住在一起，频繁地穿梭于两地。为了和闺蜜Joe（汤加文 饰）一起旅行的约定，为了自己的存在感，为了对Joe男友阿豪（孙阳 饰）懵懂的好感，她内心的冲动被点燃，“水客”成为了她的另一个身份，一段颇有“冒险”感的青春故事就此开始。",
img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2572813215.webp",
targets: [{
        name: "蜂鸟",
        page_url: "https://movie.douban.com/subject/30318230/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2544256615.webp",
        similarity: "92%",
    },
    {
        name: "伯德小姐",
        page_url: "https://movie.douban.com/subject/26588314/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2505925363.webp",
        similarity: "90%",
    },
    {
        name: "狗十三",
        page_url: "https://movie.douban.com/subject/25716096/?from=subject-page",
        img_url: "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540513831.webp",
        similarity: "90%",
    },
    {
        name: "阳光灿烂的日子",
        page_url: "https://movie.douban.com/subject/1291875/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2564685215.webp",
        similarity: "88%",
    },
    {
        name: "牯岭街少年杀人事件",
        page_url: "https://movie.douban.com/subject/1292329/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p848381236.webp",
        similarity: "86%",
    },
    {
        name: "嘉年华",
        page_url: "https://movie.douban.com/subject/27019527/?from=subject-page",
        img_url: "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2503644828.webp",
        similarity: "86%",
    },
    {
        name: "少年的你",
        page_url: "https://movie.douban.com/subject/30166972/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2572166063.webp",
        similarity: "86%",
    },
    {
        name: "佛罗里达乐园",
        page_url: "https://movie.douban.com/subject/26778790/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2496148493.webp",
        similarity: "84%",
    },
    {
        name: "天才枪手",
        page_url: "https://movie.douban.com/subject/27024903/?from=subject-page",
        img_url: "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2501863104.webp",
        similarity: "82%",
    },
    {
        name: "女孩",
        page_url: "https://movie.douban.com/subject/30194769/?from=subject-page",
        img_url: "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2519456723.webp",
        similarity: "80%",
    },
],
}, ];